version : '2.0'
networks:
  autumn_net:
services:

  autumn-mysql:
    hostname: "autumn-mysql"
    container_name: autumn-mysql
    image: mysql:5.7
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zhuang2001
    networks:
      - autumn_net

  autumn-redis:
    hostname: "autumn-redis"
    container_name: autumn-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/autumn/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/autumn/redis/redis.conf
    networks:
      - autumn_net

  autumn-minio:
    hostname: "autumn-minio"
    image: minio/minio
    container_name: autumn-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: zhuang2001
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio/
    command: server --console-address ':9001' /data
    networks:
      - autumn_net

  autumn-nginx:
    container_name: autumn-nginx
    image: autumn-nginx:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/autumn/projects/autumn-ui
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - autumn_net

  autumn-nacos:
    hostname: "autumn-nacos"
    container_name: autumn-nacos
    image: nacos/nacos-server:v2.1.0
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - autumn_net

