# 基础镜像
FROM nginx
# author
MAINTAINER autumn

# 挂载目录
VOLUME /home/autumn/projects/autumn-ui
# 创建目录
RUN mkdir -p /home/autumn/projects/autumn-ui
# 指定路径
WORKDIR /home/autumn/projects/autumn-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/autumn/projects/autumn-ui
