# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER autumn

# 挂载目录
VOLUME /home/autumn
# 创建目录
RUN mkdir -p /home/autumn
# 指定路径
WORKDIR /home/autumn
# 复制jar文件到路径
COPY ./jar/autumn-xxl-job-1.0.jar /home/autumn/autumn-xxl-job.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","autumn-xxl-job.jar"]
